version: '3'

services:
  catalogodb:
    image: mongo:3.4
  product-ms:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: product-ms
    image: product-ms-image
    depends_on:
      - catalogodb
    ports:
      - 9999:8080